### ISSUE TITLE
Unable to resolve module `expo`

### ISSUE THREAD

**Issue by loverdeveloper** [virusvn/react-native-svg-animated-linear-gradient#13]
Hi ,
Guys Check This PLEASE 👎

**Comment by sunihegde** [comment]
> Hi ,
> Guys Check This PLEASE 👎

same error here....

**Comment by sunihegde** [comment]
smae error here...
 Unable to resolve module `expo` from `..............'\node_modules\react-native-svg-animated-linear-gradient\src\index.js`: Module `expo` does not exist in the Haste module map.

**Comment by Yhozen** [comment]
Same, any workaround?

**Comment by virusvn** [comment]
Removed strict peerDependencies
