### ISSUE TITLE
undefined variable Svg (CRNA) (Android)

### ISSUE THREAD

**Issue by yash2code** [virusvn/react-native-svg-animated-linear-gradient#2]

**Comment by virusvn** [comment]
This component is based on Expo, if you want to use for CRNA, please fork this repo and setup 'react-native-svg', then change this line:
`import Expo, { Svg } from 'expo';`

to 

`import Svg  from 'react-native-svg'`;

But anyway, it's have known bug on android  (#1)

**Comment by virusvn** [comment]
Please use package [react-native-content-loader](https://github.com/aschenkel/react-native-content-loader).
