### ISSUE TITLE
Broken w/ RN 59 (expo SDK 33)

### ISSUE THREAD

**Issue by n-sviridenko** [virusvn/react-native-svg-animated-linear-gradient#20]
Prerequisites:

- `react-native-svg@9.4.0`
- `react-native-svg-animated-linear-gradient@^0.3.0`

Current behaviour:

![Simulator Screen Shot - iPhone 8 - 2019-06-22 at 18 11 45](https://user-images.githubusercontent.com/9335422/59966215-4a9c7780-9519-11e9-8224-45032999464a.png)

When changing `render` function the following way (removing all animation logic):

```js
render() {
      return (
        <AnimatedSvg height={this.props.height} width={this.props.width}>
          {this.props.children}
        </AnimatedSvg>
      );
}
```

It looks better:

![Simulator Screen Shot - iPhone 8 - 2019-06-22 at 18 12 13](https://user-images.githubusercontent.com/9335422/59966216-4bcda480-9519-11e9-929e-372afed5329a.png)

Updating to `react-native-svg@9.5.1` didn't help. I assume, there are some incompatibilities w/ the latest RN API.

**Comment by ncailleux** [comment]
Hi,

I got the same problem after updating to `expo 33` and 
`react-native-svg@9.4.0`
`react-native-svg-animated-linear-gradient@^0.3.0`
and fixed it.

<img src="https://user-images.githubusercontent.com/18699825/60019587-8278fb80-968e-11e9-92e3-c99bbc4060da.jpg" data-canonical-src="https://user-images.githubusercontent.com/18699825/60019587-8278fb80-968e-11e9-92e3-c99bbc4060da.jpg" width="300" height="640" />

With no logic as you same behaviour:

<img src="https://user-images.githubusercontent.com/18699825/60019591-8573ec00-968e-11e9-8f78-8d4935d66e50.jpg" data-canonical-src="https://user-images.githubusercontent.com/18699825/60019591-8573ec00-968e-11e9-8f78-8d4935d66e50.jpg" width="300" height="640" />

But i fixed it by changing like this the code (removing th G arround the props):
Old one:
```
<ClipPath id="clip">
    <G rotation="50" origin="100, 50">
        {this.props.children}
    </G>
</ClipPath>
```
New one:
```
<ClipPath id="clip">
    {this.props.children}
</ClipPath>
```

Current view fixed:

<img src="https://user-images.githubusercontent.com/18699825/60020376-329b3400-9690-11e9-857c-3188155875bc.jpg" data-canonical-src="https://user-images.githubusercontent.com/18699825/60020376-329b3400-9690-11e9-857c-3188155875bc.jpg" width="300" height="640" />

Maybe need an update to this package.

Good day!

**Comment by oqhadev** [comment]
thanks @ncailleux 
thats work perfect for me
its rotate problem

**Comment by n-sviridenko** [comment]
Solved in https://github.com/virusvn/react-native-svg-animated-linear-gradient/pull/19
